name: Sync Fork with upstream

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 2 * * *' # every day at 2:00 AM UTC
  push:
    branches:
     - main

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Fetch upstream
        run: |
            git remote add upstream https://github.com/HackTricks-wiki/hacktricks.git
            git fetch upstream

      - name: Update mdbook branch
        run: |
          git checkout -B mdbook upstream/master
          git push --force origin mdbook
