name: Update contents from upstream

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 2 * * *' # every day at 2:00 AM UTC

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Fetch upstream
        run: |
            git remote add upstream https://github.com/HackTricks-wiki/hacktricks.git
            git fetch upstream master

      - name: Update mdbook branch
        run: |
          git checkout -B mdbook upstream/master
          git push --force origin mdbook
  transform:
    needs: sync-fork
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed to push changes later

      - name: Get src/ from mdbook
        run: |
          git fetch origin mdbook
          git checkout origin/mdbook -- src/

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Format markdown files
        run: |
          python scripts/transform.py

      - name: Copy formatted files to obsidian vault, remove src/
        run: |
          rsync -a --delete --exclude='.obsidian/' ./src/ ./hacktricks/ 
          rm -rf ./src/

      - name: Push transformed content to main
        run: |
          # Configure git
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Commit and push only if there are changes
          git add ./hacktricks/
          git diff --cached --quiet || git commit -m "Updated contents from upstream"
          git push origin main