name: Update contents from upstream

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 2 * * *' # every day at 2:00 AM UTC

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Fetch upstream
        run: |
            git remote add upstream https://github.com/HackTricks-wiki/hacktricks.git
            git fetch upstream

      - name: Update mdbook branch
        run: |
          git checkout -B mdbook upstream/master
          git push --force origin mdbook
  transform:
    needs: sync-fork
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed to push changes later

      - name: Checkout dev branch, get src/ from mdbook
        run: |
          git checkout dev
          git fetch origin mdbook
          git checkout origin/mdbook -- src/

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Reformat markdown files
        run: |
          python scripts/transform.py

      - name: Push transformed content to main
        run: |
          # Configure git
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Add a temporary worktree for main branch
          git worktree add ../main-temp main

          # Copy transformed files to main branch worktree
          rsync -a --delete --exclude='.obsidian/' ./src/ ../main-temp/hacktricks/

          # Commit and push only if there are changes
          cd ../main-temp
          git add .
          git diff --cached --quiet || git commit -m "Update main content from mdbook"
          git push origin main

          # Clean up temporary worktree
          cd ../hacktricks-obsidian
          git worktree remove ../main-temp